version: "3.9"

services:
  databse:
    image: postgres
    container_name: database_doyoupart_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dypuser
      - POSTGRES_PASSWORD=sapiens83
      - POSTGRES_DB=doyoupartdb
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
  # driver: local
