version: "3.9"

services:
  database:
    image: postgres
    container_name: database_doyoupart_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dypuser
      - POSTGRES_PASSWORD=sapiens83
      - POSTGRES_DB=doyoupartdb
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: app_doyoupart_api
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    # driver: local
